//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormsApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinFormsApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure? You will not be able to change favourite team immediately..
        /// </summary>
        public static string chooseTeamConfirmTxt {
            get {
                return ResourceManager.GetString("chooseTeamConfirmTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croatian.
        /// </summary>
        public static string cro {
            get {
                return ResourceManager.GetString("cro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string exitConfirmTxt {
            get {
                return ResourceManager.GetString("exitConfirmTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature is not yet implemented..
        /// </summary>
        public static string featNotImplemented {
            get {
                return ResourceManager.GetString("featNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information!.
        /// </summary>
        public static string informationText {
            get {
                return ResourceManager.GetString("informationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart required to change the language or favourite team. Restart now?.
        /// </summary>
        public static string languageOrChampChange {
            get {
                return ResourceManager.GetString("languageOrChampChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Men.
        /// </summary>
        public static string men {
            get {
                return ResourceManager.GetString("men", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not choose more than .
        /// </summary>
        public static string playerUCclickTxtPart1 {
            get {
                return ResourceManager.GetString("playerUCclickTxtPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  at this time..
        /// </summary>
        public static string playerUCclickTxtPart2 {
            get {
                return ResourceManager.GetString("playerUCclickTxtPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranking tab has been enabled..
        /// </summary>
        public static string rankTabEnabledTxt {
            get {
                return ResourceManager.GetString("rankTabEnabledTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure? You will not be able to change favourite players or their images immediately..
        /// </summary>
        public static string saveInitSettingsTxt {
            get {
                return ResourceManager.GetString("saveInitSettingsTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        public static string warningText {
            get {
                return ResourceManager.GetString("warningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Women.
        /// </summary>
        public static string women {
            get {
                return ResourceManager.GetString("women", resourceCulture);
            }
        }
    }
}
